export default [
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@popperjs/core",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/popperjs/popper-core.git",
        remoteVersion: "2.9.2",
        installedVersion: "2.9.2",
        author: "Federico Zivolo",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/recoil",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "0.0.1",
        installedVersion: "0.0.1",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "axios",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/axios/axios.git",
        remoteVersion: "0.21.1",
        installedVersion: "0.21.1",
        author: "Matt Zabriskie",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "bootstrap-icons",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/twbs/icons.git",
        remoteVersion: "1.5.0",
        installedVersion: "1.5.0",
        author: "mdo",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "classnames",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/JedWatson/classnames.git",
        remoteVersion: "2.3.1",
        installedVersion: "2.3.1",
        author: "Jed Watson",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "compare-versions",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/omichelsen/compare-versions.git",
        remoteVersion: "3.6.0",
        installedVersion: "3.6.0",
        author: "Ole Michelsen",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "dotenv",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "BSD-2-Clause",
        link: "git://github.com/motdotla/dotenv.git",
        remoteVersion: "10.0.0",
        installedVersion: "10.0.0",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "electron-is-dev",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/sindresorhus/electron-is-dev.git",
        remoteVersion: "2.0.0",
        installedVersion: "2.0.0",
        author: "Sindre Sorhus",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "electron-store",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/sindresorhus/electron-store.git",
        remoteVersion: "8.0.0",
        installedVersion: "8.0.0",
        author: "Sindre Sorhus",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "fs-extra",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/jprichardson/node-fs-extra.git",
        remoteVersion: "10.0.0",
        installedVersion: "10.0.0",
        author: "JP Richardson",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "license-report",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/ironSource/license-report.git",
        remoteVersion: "4.5.0",
        installedVersion: "4.5.0",
        author: "Yaniv Kessler",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "moment",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/moment/moment.git",
        remoteVersion: "2.29.1",
        installedVersion: "2.29.1",
        author: "Iskren Ivov Chernev",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "nedb-promises",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "ISC",
        link: "git+https://github.com/bajankristof/nedb-promises.git",
        remoteVersion: "5.0.0",
        installedVersion: "5.0.0",
        author: "Kristóf Baján",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "node-fetch",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/bitinn/node-fetch.git",
        remoteVersion: "2.6.1",
        installedVersion: "2.6.1",
        author: "David Frank",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/facebook/react.git",
        remoteVersion: "17.0.2",
        installedVersion: "17.0.2",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-copy-to-clipboard",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/nkbt/react-copy-to-clipboard.git",
        remoteVersion: "5.0.3",
        installedVersion: "5.0.3",
        author: "Nik Butenko",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-dom",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/facebook/react.git",
        remoteVersion: "17.0.2",
        installedVersion: "17.0.2",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-helmet",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/nfl/react-helmet.git",
        remoteVersion: "6.1.0",
        installedVersion: "6.1.0",
        author: "NFL",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-input-range",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/davidchin/react-input-range.git",
        remoteVersion: "1.3.0",
        installedVersion: "1.3.0",
        author: "David Chin",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-intl",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "BSD-3-Clause",
        link: "git+ssh://git@github.com/formatjs/formatjs.git",
        remoteVersion: "5.20.6",
        installedVersion: "5.20.6",
        author: "Eric Ferraiuolo",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-modal",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/reactjs/react-modal.git",
        remoteVersion: "3.14.3",
        installedVersion: "3.14.3",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-router-dom",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/ReactTraining/react-router.git",
        remoteVersion: "5.2.0",
        installedVersion: "5.2.0",
        author: "React Training",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-select",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/JedWatson/react-select/tree/master/packages/react-select",
        remoteVersion: "4.3.1",
        installedVersion: "4.3.1",
        author: "Jed Watson",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-textarea-autosize",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/Andarist/react-textarea-autosize.git",
        remoteVersion: "8.3.3",
        installedVersion: "8.3.3",
        author: "Andrey Popp",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-tooltip",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/wwayne/react-tooltip.git",
        remoteVersion: "4.2.21",
        installedVersion: "4.2.21",
        author: "wwayne",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "react-twitch-embed",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/moonstar-x/react-twitch-embed.git",
        remoteVersion: "2.1.0",
        installedVersion: "2.1.0",
        author: "moonstar-x",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "recoil",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/facebookexperimental/recoil.git",
        remoteVersion: "0.3.1",
        installedVersion: "0.3.1",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "shell-quote",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+ssh://git@github.com/substack/node-shell-quote.git",
        remoteVersion: "1.7.2",
        installedVersion: "1.7.2",
        author: "James Halliday",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "socket.io",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git://github.com/socketio/socket.io.git",
        remoteVersion: "4.1.3",
        installedVersion: "4.1.3",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "socket.io-client",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/socketio/socket.io-client.git",
        remoteVersion: "4.1.3",
        installedVersion: "4.1.3",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "sqlite",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/kriasoft/node-sqlite.git",
        remoteVersion: "4.0.23",
        installedVersion: "4.0.23",
        author: "Kriasoft",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "sqlite3",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "BSD-3-Clause",
        link: "git://github.com/mapbox/node-sqlite3.git",
        remoteVersion: "5.0.2",
        installedVersion: "5.0.2",
        author: "MapBox",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "tmi.js",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git://github.com/tmijs/tmi.js.git",
        remoteVersion: "1.8.3",
        installedVersion: "1.8.3",
        author: "Schmoopiie",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "twitch",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/d-fischer/twitch.git",
        remoteVersion: "4.6.4",
        installedVersion: "4.6.4",
        author: "Daniel Fischer",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "twitch-auth",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/d-fischer/twitch.git",
        remoteVersion: "4.6.4",
        installedVersion: "4.6.4",
        author: "Daniel Fischer",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "twitch-electron-auth-provider",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/d-fischer/twitch.git",
        remoteVersion: "4.6.4",
        installedVersion: "4.6.4",
        author: "Daniel Fischer",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@babel/core",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/babel/babel.git",
        remoteVersion: "7.14.8",
        installedVersion: "7.14.8",
        author: "The Babel Team (https://babel.dev/team)",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@babel/preset-env",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/babel/babel.git",
        remoteVersion: "7.14.9",
        installedVersion: "7.14.8",
        author: "The Babel Team (https://babel.dev/team)",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@rollup/plugin-replace",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/rollup/plugins.git",
        remoteVersion: "3.0.0",
        installedVersion: "3.0.0",
        author: "Rich Harris",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/fs-extra",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "9.0.12",
        installedVersion: "9.0.12",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/moment",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/moment/moment",
        remoteVersion: "2.13.0",
        installedVersion: "2.13.0",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/node",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "16.4.10",
        installedVersion: "16.4.3",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/node-fetch",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "2.5.12",
        installedVersion: "2.5.12",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/react",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "17.0.15",
        installedVersion: "17.0.15",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/react-dom",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "17.0.9",
        installedVersion: "17.0.9",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/react-helmet",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "6.1.2",
        installedVersion: "6.1.2",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/react-router-dom",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "5.1.8",
        installedVersion: "5.1.8",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/react-select",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "4.0.17",
        installedVersion: "4.0.17",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/shell-quote",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "1.7.1",
        installedVersion: "1.7.1",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@types/tmi.js",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        remoteVersion: "1.7.2",
        installedVersion: "1.7.2",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@typescript-eslint/eslint-plugin",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/typescript-eslint/typescript-eslint.git",
        remoteVersion: "4.28.5",
        installedVersion: "4.28.5",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@typescript-eslint/parser",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "BSD-2-Clause",
        link: "git+https://github.com/typescript-eslint/typescript-eslint.git",
        remoteVersion: "4.28.5",
        installedVersion: "4.28.5",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@typescript-eslint/typescript-estree",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "BSD-2-Clause",
        link: "git+https://github.com/typescript-eslint/typescript-eslint.git",
        remoteVersion: "4.28.5",
        installedVersion: "4.28.5",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "@vitejs/plugin-react-refresh",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/vitejs/vite.git",
        remoteVersion: "1.3.6",
        installedVersion: "1.3.5",
        author: "Evan You",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "autoprefixer",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/postcss/autoprefixer.git",
        remoteVersion: "10.3.1",
        installedVersion: "10.3.1",
        author: "Andrey Sitnik",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "electron",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/electron/electron.git",
        remoteVersion: "12.0.15",
        installedVersion: "12.0.15",
        author: "Electron Community",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "electron-builder",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/electron-userland/electron-builder.git",
        remoteVersion: "22.11.11",
        installedVersion: "22.11.10",
        author: "Vladimir Krivosheev",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "eslint",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/eslint/eslint.git",
        remoteVersion: "7.32.0",
        installedVersion: "7.31.0",
        author: "Nicholas C. Zakas",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "eslint-config-prettier",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/prettier/eslint-config-prettier.git",
        remoteVersion: "8.3.0",
        installedVersion: "8.3.0",
        author: "Simon Lydell",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "eslint-plugin-prettier",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/prettier/eslint-plugin-prettier.git",
        remoteVersion: "3.4.0",
        installedVersion: "3.4.0",
        author: "Teddy Katz",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "eslint-plugin-react",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/yannickcr/eslint-plugin-react.git",
        remoteVersion: "7.24.0",
        installedVersion: "7.24.0",
        author: "Yannick Croissant",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "postcss",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/postcss/postcss.git",
        remoteVersion: "8.3.6",
        installedVersion: "8.3.6",
        author: "Andrey Sitnik",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "prettier",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/prettier/prettier.git",
        remoteVersion: "2.3.2",
        installedVersion: "2.3.2",
        author: "James Long",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "rollup",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/rollup/rollup.git",
        remoteVersion: "2.55.1",
        installedVersion: "2.54.0",
        author: "Rich Harris",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "rollup-plugin-esbuild",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/egoist/rollup-plugin-esbuild.git",
        remoteVersion: "4.5.0",
        installedVersion: "4.5.0",
        author: "EGOIST",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "rollup-plugin-replace",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/rollup/rollup-plugin-replace.git",
        remoteVersion: "2.2.0",
        installedVersion: "2.2.0",
        author: "Rich Harris",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "sass",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/sass/dart-sass.git",
        remoteVersion: "1.37.0",
        installedVersion: "1.36.0",
        author: "Natalie Weizenbaum",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "stylelint-config-standard",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/stylelint/stylelint-config-standard.git",
        remoteVersion: "22.0.0",
        installedVersion: "22.0.0",
        author: "stylelint",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "tailwindcss",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/tailwindlabs/tailwindcss.git",
        remoteVersion: "2.2.7",
        installedVersion: "2.2.7",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "ts-node",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git://github.com/TypeStrong/ts-node.git",
        remoteVersion: "10.1.0",
        installedVersion: "10.1.0",
        author: "Blake Embrey",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "tsconfig-paths",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "https://github.com/dividab/tsconfig-paths",
        remoteVersion: "3.10.1",
        installedVersion: "3.10.1",
        author: "Jonas Kello",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "typescript",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "Apache-2.0",
        link: "git+https://github.com/Microsoft/TypeScript.git",
        remoteVersion: "4.3.5",
        installedVersion: "4.3.5",
        author: "Microsoft Corp.",
    },
    {
        department: "kessler",
        relatedTo: "stuff",
        name: "vite",
        licensePeriod: "perpetual",
        material: "material",
        licenseType: "MIT",
        link: "git+https://github.com/vitejs/vite.git",
        remoteVersion: "2.4.4",
        installedVersion: "2.4.3",
        author: "Evan You",
    },
];
